### ISSUE TITLE
Se debe poder recuperar una lista ordenada de las claves

### ISSUE THREAD

**Issue by evolentini** [javosmar/testing_tdd#1]
El requisito no dice que la lista debe estar ordenada, sino que se puede obtener una lista de todas las claves (solo de las claves), y que esta lista esta ordenada. No hay problema que vos mantengas la lista en si ordenada, pero eso debería ser transparente al usuario (es decir deberías hacerlo dentro del add). Ademas no hay una función para recuperar la lista de claves.

**Comment by javosmar** [comment]
Perfecto! ahí entendí ese requerimiento y lo corregí. Eliminé la devolución de la lista ordenada y solo devuelvo el array de claves ordenado.
