### ISSUE TITLE
No se aplicó correctamente la metodología TDD

### ISSUE THREAD

**Issue by evolentini** [javosmar/testing_tdd#2]
Ninguna de las pruebas escritas requiere que la función find devuelva un valor false, es decir que hay codigo escrito sin que una prueba lo haya requerido.

https://github.com/javosmar/testing_1/blob/d41677faba2f620fd087583d2f83aa98fb3ecb3b/src/lista.js#L14-L24

**Comment by javosmar** [comment]
Añadí la prueba que genera el desarrollo de la función find para que devuelva false en caso de no encontrar el elemento buscado.

**Comment by evolentini** [comment]
No entiendo porque cuando no hay elementos retorno NaN y cuando no se encuentra retorna false, lo más razonable es que siempre que no se encuentra el elemento retorne el mismo valor, cualquiera de los dos, pero siempre el mismo.

**Comment by javosmar** [comment]
Genial, ahí limpié el código y unifiqué el dato devuelto para que sea NaN en caso de no encontrar un elemento en particular o ninguno
